### ISSUE TITLE
plugin unsupported in  phonegap

### ISSUE THREAD

**Issue by jay6404** [nchutchind/cordova-plugin-app-launcher#15]
I have deloped one app in PhoneGap using this plugin i have tested and it's fine but when i try to build using PhoneGap build using my PhoneGap adobe id it shows me this error plugin unsupported: com.hutchind.cordova.plugins.launcher .
Does anyone have sloution?

**Comment by cosmin-petrescu** [comment]
Cordova has also an issue and try to install "com.hutchind.cordova.plugins.launcher" on each prepare. This is cause by the plugin.xml -> widget.id field.
Maybe PhoneGap issue is generated by the same field.

**Comment by hewittv** [comment]
In the short-term try manually editing your config.xml:
    **Old**: <plugin name="com.hutchind.cordova.plugins.launcher" spec="^0.3.0" />
    **New**: <plugin name="cordova-plugin-app-launcher" spec="^0.3.0" />

The problem appears to be due to the plugin.xml using the following: id="com.hutchind.cordova.plugins.launcher". I believe it should be id="cordova-plugin-app-launcher" and will drop a note to the plugin owner.

**Comment by nchutchind** [comment]
I have updated the plugin id in the package.json and plugin.xml to match the name of the project on npm. Hopefully this will enable PhoneGap Build to identify it successfully. Thank you, @hewittv for contacting me.
