### ISSUE TITLE
Launch app itself

### ISSUE THREAD

**Issue by kennrll18** [nchutchind/cordova-plugin-app-launcher#16]
Can i use this to launch my app itself? For example my app was force closed and there was a trigger that will launch my app.  
Also, how can i find my app's URI?

**Comment by d3w201** [comment]
any response?

**Comment by richenyadav001** [comment]
@kennrll18 how will you get the trigger of force close ?

Also, how can i find my app's URI?
You have to register URI for your app.

**Comment by nchutchind** [comment]
If your app has been closed, what would trigger the launch of your app? You'd have to have some secondary service running that would detect your app getting closed and launch it again.
