### ISSUE TITLE
Error Application is not installed

### ISSUE THREAD

**Issue by umpol** [nchutchind/cordova-plugin-app-launcher#6]
Hello,

I try to launch com.android.packageinstaller to install file.apk 

my code is 

var sdcard = "file:///sdcard/apk/";
var file1 = sdcard + "myapp.apk";

 var successCallback = function(data) {
        alert("Success!");
     };
    var errorCallback = function(errMsg) {
        alert("Error! " + errMsg);
    }

```
window.plugins.launcher.canLaunch({
    packageName:'com.android.packageinstaller',
    uri:file1,
}, successCallback, errorCallback);
```

When I run the command I've got error msg

"Error Application is not installed"

Please suggest

**Comment by mirco1000** [comment]
hello, (iOS)  build failed !
