### ISSUE TITLE
build failed (iOS)

### ISSUE THREAD

**Issue by mirco1000** [nchutchind/cordova-plugin-app-launcher#7]
hello, work fine on android but  trying to build my app for iOS it give this 
build failed
error code 65

/Users/daren/myapp/platforms/ios/myapp/Plugins/com.hutchind.cordova.plugins.launcher/Launcher.m:14:40: No visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString:'

/Users/daren/myapp/platforms/ios/myapp/Plugins/com.hutchind.cordova.plugins.launcher/Launcher.m:17:40: No visible @interface for 'CDVPluginResult' declares the selector 'toErrorCallbackString:'

/Users/daren/myapp/platforms/ios/myapp/Plugins/com.hutchind.cordova.plugins.launcher/Launcher.m:21:39: No visible @interface for 'CDVPluginResult' declares the selector 'toErrorCallbackString:'

/Users/daren/myapp/platforms/ios/myapp/Plugins/com.hutchind.cordova.plugins.launcher/Launcher.m:35:40: No visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString:'

/Users/daren/myapp/platforms/ios/myapp/Plugins/com.hutchind.cordova.plugins.launcher/Launcher.m:38:40: No visible @interface for 'CDVPluginResult' declares the selector 'toErrorCallbackString:'

/Users/daren/myapp/platforms/ios/myapp/Plugins/com.hutchind.cordova.plugins.launcher/Launcher.m:42:39: No visible @interface for 'CDVPluginResult' declares the selector 'toErrorCallbackString:'

**Comment by sevenwithawp** [comment]
Any solutions for this issue?

**Comment by mirco1000** [comment]
you can use use startapp plugin and don't forget to edit .plist

**Comment by mrmasterix** [comment]
I have the same issue. When you will resolve it?

**Comment by ziobudda** [comment]
Any news ?

**Comment by wizzed** [comment]
This is probably due to ios 4.0.0 and above, I'm looking for a solution too.

**Comment by ziobudda** [comment]
@wizzed see "ios writeJavascript depricated " from mrmasterix comment.
